# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 178ba491ee18db280f0349ce4465285921774a21ff9e7b615756b6eccd92cb1bb54c0f4bd23f7e8d3d930c5fe00ed20b6691497d1778c12dc71fe683783d3d45

test:
  secret_key_base: d5a62923656a35a314a132854e490eeb7a7345f1e656b40dfc63e558d365f2cc936c49ac8b1cf9cfa66a5a72e96ad56116425d6e0d07899ec914ff5cfa5ceea5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
